#!/usr/bin/env bash
#script that displays 0-100 and displaying certain words
#at certain number multiples

fb="FizzBuzz"
f="Fizz"
b="Buzz"
c=1

while [ $c -le 100 ]
do

	if [ $((c % 3)) -eq 0 ] && [ $((c % 5)) -eq 0 ]
	then
		echo $fb
		

	elif [ $((c % 3)) -eq 0 ] 
	then
		echo $f
	

	elif [ $((c % 5)) -eq 0 ] 
	then
		echo $b
	

	else
		echo $c
	


	fi

	((c++))


	
done



  
