#!/usr/bin/env bash
#
#
#

fn='/etc/passwd'

while IFS=: read -r username _ userid groupid info homedir shell

do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid place is protected by the passcode x, more info about the user here: $info"

done < $fn


  
