#!/usr/bin/env bash
#best school ten times using while if,elif, and else loops


bs=1

while [ $bs -le 10 ]
do
	if [ $bs = 4 ]
	then echo bad luck
	elif [ $bs = 8 ]
	then echo good luck
	else
		echo Best School
	fi
	((bs++))
done


  
