#!/usr/bin/env bash
#best school ten times using while and case



bs=1

while [ $bs -le 10 ]
do
	echo $bs

	case $bs in
		4) echo bad luck from China
			;;
		9) echo bad luck from Japan
			;;
		17) echo bad luck from Italy
			;;
	esac

	((bs++))

done

  
