#!/usr/bin/env bash
#script that gives you information about the school file with
#if and else

s=/school

if [ -f "$s" ]

then


	echo school file exists

	if [ ! -s "$s" ]
	then
		echo school file is empty
		echo school is a regular file
	else
		echo school file is not empty
		echo school is a regular file
	fi


else


	echo school file does not exist


fi

  
