#!/usr/bin/env bash
#displays list of currently running processes
#

x=1

echo $$ > /var/run/myscript.pid

while [ $x -gt 0 ]
do
	trap 'echo "I hate the kill command" ; rm -rf /var/run/myscript.pid; exit' SIGTERM
	trap "echo Y U no love me?!" SIGINT
	printf "To infinity and beyond\n"
	trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT
	((x++))
	sleep 2
done

